spring.datasource.url=mysql/jdbc/3306
spring.datasource.username="saiprasad"
spring.datasource.password="saiprasad123"
spring.datasource.driver="mysql-driver"

spring.jpa.hibernate.ddl-auto="create"
spring.jpa.hibernate.show-sql=true
